FROM nginx:stable

COPY dist/petro /usr/share/nginx/html

# COPY compose/nginx.conf /etc/nginx/nginx.conf

# ADD php/ /usr/share/nginx/html/php

# ADD uploads/ /usr/share/nginx/html/uploads

# Build: docker build -t pmutisya/profile:latest .

# PUSH: docker push pmutisya/profile:latest

# docker run pmutisya/profile:latest